### PR TITLE
Bug/human

### LINKED ISSUE #12: bug in ISO86601 parser
this date is not parsed correctly for some reason:

```
2006-09-15 20:50:06"
```

please check:

  https://github.com/fnordcorp/libstx/blob/master/src/stx/human_test.cc#L73

### PR DESCRIPTION
**Pull request by lauraschlimmer**
Fixed #12

### CODE REVIEW

File: src/stx/human.cc [hunk 1]
```diff
@@ -59,6 +59,11 @@ Option<UnixTime> Human::parseTime(
     return Some(UnixTime(civil.get()));
   }
 
+  auto civil_time = CivilTime::parseString(str);
```
Comment (lauraschlimmer) [inline src/stx/human.cc:62]: should I better reuse civil here?
